---
apiVersion: v1
kind: Service
metadata:
  name: nginx-${DEPLOYMENT}
  labels:
    k8s-app: nginx
spec:
  type: NodePort
  selector:
    k8s-app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
